pipeline{
    agent any
    stages{
        stage('Build Application'){
            steps{
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post{
                success{
                    echo 'Mow archiving the Artifact....'
                    archiveArtifacts artifacts:"**/*.war"
                }
            }
        }
    }
}