pipeline{
    agent any
    stages {
        stage('Build Application'){
            steps{
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post{
                success{
                    echo 'Now archiving the Artifact....'
                    archiveArtifacts artifacts:"**/*.war"
                }
            }
        }
        stage('Deploy in staging Environment'){
            steps{
                build job: 'Deploy_application_Staging_Env'
            }
        }

       }
    }
}